name: Test Action

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  checks: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3

      - name: Check out repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Node.js dependencies
        run: npm install
        
      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: phamelink/lint-action@v1.13.0
        with:
          continue_on_error: true
          prettier: true
          auto_fix: true
          black: false
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: false
          prettier_auto_fix: false
          prettier_extensions: "css,html,js,json,jsx,less,md,scss,ts,tsx,vue,yaml,yml"
          neutral_check_on_warning: true
